import React, { useState } from 'react';
import { Sparkles, Send, Cpu, AlertCircle } from 'lucide-react';
import { CodeViewer } from './CodeViewer';
import { apiFetch } from '../lib/api';
export const GeminiSynthesis: React.FC = () => {
 const [prompt,setPrompt]=useState(''); const [selectedModel,setSelectedModel]=useState('gemini-3.6-flash'); const [systemInstruction,setSystemInstruction]=useState('You are Gemini inside Mandela Matrix OS. Synthesize clear, structured architectural answers for matrix, core, and build tasks.'); const [isLoading,setIsLoading]=useState(false); const [synthesisResult,setSynthesisResult]=useState(''); const [errorMsg,setErrorMsg]=useState<string|null>(null);
 const templates=['Provide a complete Room database architecture and migration plan for Kotlin and Flow.','Synthesize Clean Architecture with UseCases, Repositories, ViewModels and Compose UI.','Design an offline-first sync engine using Coroutines, WorkManager and Room.','Synthesize a Material 3 dark terminal theme for Compose.'];
 const handleSynthesize=async()=>{if(!prompt.trim()||isLoading)return;setIsLoading(true);setErrorMsg(null);setSynthesisResult('');try{const r=await apiFetch('/api/gemini/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,systemInstruction,model:selectedModel})});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{throw new Error(`Backend returned invalid JSON (HTTP ${r.status}).`)}if(!r.ok)throw new Error(d.error||`Gemini request failed (HTTP ${r.status}).`);setSynthesisResult(d.result||'');}catch(e:any){console.error(e);setErrorMsg(e?.message||'Backend connection failed.');}finally{setIsLoading(false);}};
 return <div className="space-y-6 font-mono"><div className="p-4 rounded border border-[#A855F7]/40 bg-black/80"><div className="flex items-center gap-3"><Sparkles className="w-6 h-6 text-[#A855F7]"/><div><h2 className="text-base font-bold text-[#A855F7]">CORE GEMINI AI - MATRIX SYNTHESIS</h2><p className="text-xs text-gray-400">Server-side Gemini API core</p></div></div></div><div className="p-4 rounded border border-[#A855F7]/30 bg-black/90 space-y-4"><select value={selectedModel} onChange={e=>setSelectedModel(e.target.value)} className="bg-black border border-[#A855F7]/50 text-[#A855F7] text-xs p-2 rounded"><option value="gemini-3.6-flash">gemini-3.6-flash</option><option value="gemini-3.1-pro-preview">gemini-3.1-pro-preview</option></select><textarea value={systemInstruction} onChange={e=>setSystemInstruction(e.target.value)} rows={2} className="w-full bg-[#0D0208] border border-[#A855F7]/40 rounded p-3 text-xs text-purple-200"/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} placeholder="Describe exactly what you want Gemini to build..." className="w-full bg-[#0D0208] border border-[#A855F7]/40 rounded p-3 text-xs text-[#A855F7]"/><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{templates.map((x,i)=><button key={i} onClick={()=>setPrompt(x)} className="text-left p-2 rounded border border-[#A855F7]/30 text-xs text-gray-300">{x}</button>)}</div><button onClick={handleSynthesize} disabled={isLoading||!prompt.trim()} className="flex items-center gap-2 px-6 py-2.5 rounded bg-[#A855F7] text-black font-bold text-xs disabled:opacity-50">{isLoading?<><Cpu className="w-4 h-4 animate-spin"/>SYNTHESIZING...</>:<><Send className="w-4 h-4"/>START GEMINI SYNTHESIS</>}</button></div>{errorMsg&&<div className="p-3 rounded border border-red-500/50 bg-red-950/30 text-red-300 text-xs"><AlertCircle className="inline w-4 h-4 mr-2"/>{errorMsg}</div>}{synthesisResult&&<div className="p-4 rounded border border-[#A855F7]/40 bg-black/90"><div className="text-xs text-purple-200 whitespace-pre-wrap">{synthesisResult}</div>{(synthesisResult.includes('class ')||synthesisResult.includes('fun '))&&<CodeViewer code={synthesisResult} filename="GeminiSynthesizedArchitecture.kt" language="kotlin"/>}</div>}</div>;
};
